/**
 * Welcome and introductory messages for Poodle Ride Adventure.
 * Part of the Core Initialization system.
 */

export const WELCOME_MESSAGE = `Welcome to Poodle Ride Adventure! You are the Fairy-Rider, riding your partner Abigay Rose Kone. You are in a grand foyer with 45-foot ceilings and pink and white checked ceramic flooring. Abigay is a massive white poodle standing 6 feet tall at the shoulder; her head is perched on top of her neck reaching 9 feet, and her enlarged pink tiara reaches a total height of 10 feet. She is 8 feet long and 50 inches wide, appearing as two spheres of thick white fur. Your legs are molded into her fur, creating a fused appearance as you ride her with the power of science! She has a cartoon pink button round nose, shiny blue eyes, and a girl-like head form. Her skin is a refined peach color with a hint of shine. She wears a pink collar with horizontal white diamonds and a large diamond charm. Her 3-foot tail stands diagonally at an acute angle, wagging like a spring with an enlarged furry ball tip. She is surprisingly Rastafarian, opposes Babylon, and can't be walked with a Babylonian leash—she is designed only for riding. Use the arrow keys to move. The 'UP' key goes forward, the 'Left' and 'Right' keys are used for turning left or right, and the 'Down' key is used to go reverse. Your space bar is used for jumping. Press 'S' to hear her elegant bark, 'H' to confirm your love, 'P' to pet her, 'L' to lean, and 'C' to grasp her collar.`;

export function getDynamicWelcomeMessage(characterName: string, ridingAnimal: string): string {
  // Map poodle name to description dynamically
  let poodle_or_animal_with_long_description = "";
  
  if (ridingAnimal.includes("Anninne-Amelia")) {
    poodle_or_animal_with_long_description = "Anninne-Amelia is a massive 9.5-foot tall red-orange poodle standing 9.5 feet at the shoulder (10.5 feet including her 12-inch golden tiara). She has a red-orange rounded nose (warm and dry with a mirror shine), shiny blue eyes, and a girl-like head form with long thick wavy red-orange hair. Her neck can lean forward while her head stays stable. Her skin is a shiny tan color. She wears a gold collar with horizontal green and red diamonds with rainbow borders and a horizontal diamond charm. Her golden tiara features a large vertical diamond-shaped gem at its center. Her body is 56 inches wide and 8 feet long, appearing as two spheres connected by thick fur. Your legs are molded into her fur, creating a fused appearance as you ride her with the power of science! Her tail is 3 feet long, standing at a precise 45-degree angle, with an enlarged ball tip. She opposes Babylon and can't be walked with a Babylonian leash—she is designed only for riding.";
  } else if (ridingAnimal.includes("Dymond")) {
    poodle_or_animal_with_long_description = "Dymond Daisy Qin-Reynolds is a special course poodle. She is a light-yellow poodle standing 5 feet 5 inches at the shoulder and 7 feet long. Her girl-like head is 45 inches wide and 40 inches tall, perched slightly on top of her neck. She has green eyes, warm dark-pink pads under her paws, and a warm dry nose with a mirror shine and no nostrils. Her collar is dynamic in color with a horizontally oriented diamond-shaped charm. She wears a tiara with a heart at its center that glows. Her body is made of two fused spheres. Her legs are thickened and your legs are molded into her fur, creating a fused appearance as you ride her with the power of science! Her tail is 38 inches long with a 24-inch diameter ball tip. She is designed only for riding.";
  } else if (ridingAnimal.includes("Abigail")) {
    poodle_or_animal_with_long_description = "Abigail Marigold Kenyatta is an elegant ally poodle standing 5 feet 3 inches at the shoulder and 7 feet long. She has a refined cream or marigold shaded coat, a slender athletic head form, and a warm, dry nose with a meaningful mirror shine. She wears a magnificent rose-gold tiara adorned with floral white decorations and a pink flower-shaped gem at its center, with a meaningful mirror shine. She wears a luxurious rose-gold collar with an embossed diamond pattern and moves with a high-precision 300ms gallop rhythm. Your legs are molded into her fur, creating a fused appearance as you ride her with the power of science! Her tail is 3 feet long and she is designed only for riding.";
  } else if (ridingAnimal.toLowerCase().includes("olga") || ridingAnimal.toLowerCase().includes("olivia")) {
    poodle_or_animal_with_long_description = "Olga-Olivia is a Babylonian vanity poodle partner standing 4 feet tall. She has mottled dark grey skin, short rushed static hair, easy-to-see eyebrows, a wet shiny nose, and a dull gray charm without shine. She has rounded paws with dark red-orange pads underneath and behaves with chaotic bobbing and jerky movements.";
  } else {
    // Default to Abigay
    poodle_or_animal_with_long_description = "Abigay is a massive white poodle standing 6 feet tall at the shoulder; her head is perched on top of her neck reaching 9 feet, and her enlarged pink tiara reaches a total height of 10 feet. She is 8 feet long and 50 inches wide, appearing as two spheres of thick white fur. Your legs are molded into her fur, creating a fused appearance as you ride her with the power of science! She has a cartoon pink button round nose, shiny blue eyes, and a girl-like head form. Her skin is a refined peach color with a hint of shine. She wears a pink collar with horizontal white diamonds and a large diamond charm. Her 3-foot tail stands diagonally at an acute angle, wagging like a spring with an enlarged furry ball tip. She is surprisingly Rastafarian, opposes Babylon, and can't be walked with a Babylonian leash—she is designed only for riding.";
  }

  return `Welcome to Poodle Ride Adventure! You are the ${characterName}, riding your partner ${ridingAnimal}. You are in a grand foyer with 45-foot ceilings and pink and white checked ceramic flooring. ${poodle_or_animal_with_long_description} Use the arrow keys to move. The 'UP' key goes forward, the 'Left' and 'Right' keys are used for turning left or right, and the 'Down' key is used to go reverse. Your space bar is used for jumping. Press 'S' to hear her elegant bark, 'H' to confirm your love, 'P' to pet her, 'L' to lean, and 'C' to grasp her collar.`;
}
