import { POODLE_CORE, ABIGAY_DESCRIPTION, GAME_CORE_FEATURES } from '../General';

export const AbigayCore = {
  POODLE_CORE,
  ABIGAY_DESCRIPTION,
  GAME_CORE_FEATURES
};

export { POODLE_CORE, ABIGAY_DESCRIPTION, GAME_CORE_FEATURES };
