/**
 * System/Registry/AI/In-Game/Category/Arena/General/index.tsx
 * 
 * Master Registry for Arena Spatial Metadata.
 * Centralizes all manor room, porch, and walkway dimensions to 
 * eliminate scattered magic numbers.
 */

export interface AreaRegistryDefinition {
  id: string;
  name: string;
  width: number;
  height: number;
  material: 'Hardwood' | 'Grass' | 'Carpet' | 'Stone' | 'Dirt' | 'Concrete';
  isOutdoor: boolean;
}

export interface ArenaRegistryConfigType {
  subsystem: 'Arena';
  areas: AreaRegistryDefinition[];
  globalConstants: {
    GRID_SIZE: number;
    CLASSIC_GRID_SIZE: number;
    WALKWAY_HEIGHT: number;
    CEILING_HEIGHT: number;
  };
}

export const ArenaRegistryConfig: ArenaRegistryConfigType = {
  subsystem: 'Arena',
  globalConstants: {
    GRID_SIZE: 2000,
    CLASSIC_GRID_SIZE: 2000,
    WALKWAY_HEIGHT: 25,
    CEILING_HEIGHT: 45,
  },
  areas: [
    { id: 'Foyer', name: 'Grand Foyer', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'Garden', name: 'Simulated Garden', width: 8000, height: 2000, material: 'Grass', isOutdoor: true },
    { id: 'FrontPorch', name: 'Front Porch', width: 8000, height: 250, material: 'Hardwood', isOutdoor: true },
    { id: 'BackPorch', name: 'Back Porch', width: 8000, height: 250, material: 'Hardwood', isOutdoor: true },
    { id: 'Sidewalk', name: 'Sidewalk', width: 8000, height: 40, material: 'Concrete', isOutdoor: true },
    { id: 'Street', name: 'Street', width: 8000, height: 60, material: 'Concrete', isOutdoor: true },
    { id: 'AdventureHouseFoyer', name: 'Adventure House Foyer', width: 30, height: 20, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventureHouseHallway', name: 'Adventure House Hallway', width: 8, height: 700, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventureHouseTeaRoom', name: 'Adventure House Tea Room', width: 50, height: 60, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventureHouseNarrowHallway', name: 'Adventure House Narrow Hallway', width: 4, height: 100, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventureHouseMusicRoom', name: 'Adventure House Music Room', width: 20, height: 20, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventureHouseBridgeHallway', name: 'Adventure House Bridge Hallway', width: 10, height: 80, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventureHouseTrenchHallway', name: 'Adventure House Trench Hallway', width: 70, height: 300, material: 'Hardwood', isOutdoor: false },
    { id: 'AdventurePath', name: 'Adventure Path', width: 20, height: 10560, material: 'Dirt', isOutdoor: true },
    { id: 'HedgePath', name: 'Hedge Path', width: 20, height: 21120, material: 'Grass', isOutdoor: true },
    { id: 'RastafariCave', name: 'Rastafari Cave', width: 40, height: 42240, material: 'Stone', isOutdoor: false },
    { id: 'Overpass', name: 'Overpass', width: 20, height: 15840, material: 'Concrete', isOutdoor: true },
    { id: 'Suburb', name: 'Suburb', width: 20, height: 5280, material: 'Concrete', isOutdoor: true },
    { id: 'OpenTrench', name: 'Open Trench', width: 20, height: 26400, material: 'Dirt', isOutdoor: true },
    { id: 'CellarRamp', name: 'Cellar Ramp', width: 30, height: 200, material: 'Stone', isOutdoor: false },
    { id: 'Cellar', name: 'Manor Cellar', width: 2000, height: 2000, material: 'Stone', isOutdoor: false },
    { id: 'RuggedPlayField', name: 'Rugged Play Field', width: 2000, height: 2000, material: 'Grass', isOutdoor: true },
    { id: 'MeditationHall', name: 'Meditation Hall', width: 2000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'AnimalRideMeditationRoom', name: 'Animal Ride Meditation Room', width: 180, height: 90, material: 'Hardwood', isOutdoor: false },
    { id: 'MeditationHallWest', name: 'Meditation Hall West', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'MeditationHallEast', name: 'Meditation Hall East', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'RuggedPlayFieldWest1', name: 'Rugged Play Field West 1', width: 1000, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'RuggedPlayFieldWest2', name: 'Rugged Play Field West 2', width: 1000, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'RuggedPlayFieldEast1', name: 'Rugged Play Field East 1', width: 1000, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'RuggedPlayFieldEast2', name: 'Rugged Play Field East 2', width: 1000, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'FoyerWest1', name: 'Foyer West 1', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'FoyerWest2', name: 'Foyer West 2', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'FoyerEast1', name: 'Foyer East 1', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'FoyerEast2', name: 'Foyer East 2', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'Kitchen', name: 'Kitchen', width: 1000, height: 500, material: 'Stone', isOutdoor: false },
    { id: 'DishWasherArea', name: 'DishWasher Area', width: 1000, height: 500, material: 'Stone', isOutdoor: false },
    { id: 'Soca_Path', name: 'Soca Path', width: 300, height: 10000, material: 'Dirt', isOutdoor: true },
    { id: 'AllisonsPorch', name: "Allison's Porch", width: 1000, height: 300, material: 'Hardwood', isOutdoor: true },
    { id: 'AllisonsFoyer', name: "Allison's Foyer", width: 500, height: 500, material: 'Hardwood', isOutdoor: false },
    { id: 'Allisons2ndFloor', name: "Allison's 2nd Floor", width: 1000, height: 700, material: 'Hardwood', isOutdoor: false },
    { id: 'Allisons3rdFloor', name: "Allison's 3rd Floor", width: 1000, height: 700, material: 'Hardwood', isOutdoor: false },
    { id: 'AllisonsRooftop', name: "Allison's Rooftop", width: 1000, height: 700, material: 'Concrete', isOutdoor: true },
    { id: 'AllisonsRestaurant', name: "Allison's Restaurant", width: 500, height: 200, material: 'Hardwood', isOutdoor: false },
    { id: 'AllisonsRestaurantOutdoor', name: "Allison's Restaurant Outdoor", width: 500, height: 200, material: 'Hardwood', isOutdoor: true },
    { id: 'AllisonsStore', name: "Allison's Store", width: 235, height: 200, material: 'Hardwood', isOutdoor: false },
    { id: 'AllisonsMountainsWarpRoom', name: "Allison's Mountains Warp Room", width: 200, height: 480, material: 'Stone', isOutdoor: false },
    { id: 'Barn', name: 'Barn', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'Barn2ndFloor', name: 'Barn 2nd Floor', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'ElevatedPath', name: 'Elevated Path', width: 15, height: 1000, material: 'Hardwood', isOutdoor: true },
    { id: 'AllisonsAmusementParkHouse', name: "Allison's Amusement Park House", width: 3000, height: 3000, material: 'Hardwood', isOutdoor: false },
    { id: 'GrandBallroom', name: 'Grand Ballroom', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'TheGrandPlayground', name: 'The Grand Playground', width: 2000, height: 2000, material: 'Grass', isOutdoor: true },
    { id: 'SimulatedGardenArea', name: 'Simulated Garden Area', width: 2000, height: 2000, material: 'Grass', isOutdoor: true },
    { id: 'GrandDiningRoom', name: 'Grand Dining Room', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'GrandDiningRoomExtra', name: 'Grand Dining Room Extra', width: 1000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'GrandDiningRoomEast', name: 'Grand Dining Room East', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'RecyclingRoom', name: 'Recycling Room', width: 1000, height: 1000, material: 'Stone', isOutdoor: false },
    { id: 'MeditationHallLibrary', name: 'Meditation Hall Library', width: 2000, height: 1000, material: 'Hardwood', isOutdoor: false },
    { id: 'LobbyStairwayAndRamps', name: 'Lobby Stairway And Ramps', width: 1000, height: 1000, material: 'Stone', isOutdoor: false },
    { id: 'WestManorPath', name: 'West Manor Path', width: 50, height: 7500, material: 'Dirt', isOutdoor: true },
    { id: 'EastManorPath', name: 'East Manor Path', width: 50, height: 7500, material: 'Dirt', isOutdoor: true },
    { id: 'SouthwestMezzanineStairwayAndRamps', name: 'Southwest Mezzanine Stairway And Ramps', width: 1000, height: 1000, material: 'Stone', isOutdoor: false },
    { id: 'GrandPlaygroundPlaceholder1', name: 'Grand Playground Placeholder 1', width: 2000, height: 2000, material: 'Grass', isOutdoor: true },
    { id: 'GrandPlaygroundPlaceholder2', name: 'Grand Playground Placeholder 2', width: 2000, height: 2000, material: 'Grass', isOutdoor: true },
    { id: 'CommunalStore', name: 'Communal Store', width: 1000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'EastGrandArcade', name: 'East Grand Arcade', width: 2000, height: 2000, material: 'Stone', isOutdoor: false },
    { id: 'EastCommunalSpace', name: 'East Communal Space', width: 1000, height: 1500, material: 'Stone', isOutdoor: false },
    { id: 'WestCommunalSpace', name: 'West Communal Space', width: 1000, height: 1500, material: 'Stone', isOutdoor: false },
    { id: 'GrandArcadeExtension', name: 'Grand Arcade Extension', width: 1000, height: 1000, material: 'Stone', isOutdoor: false },
    { id: 'VendingMachineRoomEast', name: 'Vending Machine Room East', width: 500, height: 500, material: 'Stone', isOutdoor: false },
    { id: 'VendingMachineRoomWest', name: 'Vending Machine Room West', width: 500, height: 500, material: 'Stone', isOutdoor: false },
    { id: 'WestGrandArcade', name: 'West Grand Arcade', width: 2000, height: 2000, material: 'Stone', isOutdoor: false },
    { id: 'TheGrandGym', name: 'The Grand Gym', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'NarrowDressageGym', name: 'Narrow Dressage Gym', width: 1000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'EmployeesLivingQuarters', name: 'Employees Living Quarters', width: 2000, height: 1000, material: 'Carpet', isOutdoor: false },
    { id: 'RastaManor2ndFloor', name: 'Rasta Manor 2nd Floor', width: 8000, height: 7000, material: 'Hardwood', isOutdoor: false },
    { id: 'RastaManor3rdFloor', name: 'Rasta Manor 3rd Floor', width: 8000, height: 7000, material: 'Hardwood', isOutdoor: false },
    { id: 'ManorTransitionPlaceholder', name: 'Manor Transition Placeholder', width: 2000, height: 2000, material: 'Stone', isOutdoor: false },
    { id: 'MiniManor', name: 'Mini Manor', width: 175, height: 200, material: 'Hardwood', isOutdoor: false },
    { id: 'MiniFrontPorch', name: 'Mini Front Porch', width: 175, height: 62.5, material: 'Hardwood', isOutdoor: true },
    { id: 'MiniBackPorch', name: 'Mini Back Porch', width: 175, height: 62.5, material: 'Hardwood', isOutdoor: true },
    { id: 'MiniGarden', name: 'Mini Garden', width: 175, height: 50, material: 'Grass', isOutdoor: true },
    { id: 'MiniStreet', name: 'Mini Street', width: 1000, height: 60, material: 'Concrete', isOutdoor: true },
    { id: 'MiniSidewalk', name: 'Mini Sidewalk', width: 1000, height: 40, material: 'Concrete', isOutdoor: true },
    { id: 'MiniWestManorPath', name: 'Mini West Manor Path', width: 40, height: 200, material: 'Dirt', isOutdoor: true },
    { id: 'MiniEastManorPath', name: 'Mini East Manor Path', width: 40, height: 200, material: 'Dirt', isOutdoor: true },
    { id: 'WesternWarpRoom', name: 'Western Warp Room', width: 250, height: 185, material: 'Stone', isOutdoor: false },
    { id: 'GardenSpecificWarpRoom', name: 'Garden Specific Warp Room', width: 250, height: 100, material: 'Stone', isOutdoor: false },
    { id: 'SoutheastCoastWarpRoom', name: 'Southeast Coast Warp Room', width: 250, height: 100, material: 'Stone', isOutdoor: false },
    { id: 'FuturisticFrenzy', name: 'Futuristic Frenzy', width: 200, height: 250, material: 'Concrete', isOutdoor: true },
    { id: 'BabylonIsFinallyFallen', name: 'Babylon Is Finally Fallen', width: 200, height: 250, material: 'Concrete', isOutdoor: true },
    { id: 'WesternTarsisEffect', name: 'Western Tarsis Effect', width: 1100, height: 20, material: 'Stone', isOutdoor: false },
    { id: 'PablotsFarm', name: "Pablot's Farm", width: 2087, height: 2087, material: 'Grass', isOutdoor: true },
    { id: 'PablotsPonyField', name: "Pablot's Pony Field", width: 20000, height: 20, material: 'Grass', isOutdoor: true },
    { id: 'BoilerRoom', name: 'Boiler Room', width: 8000, height: 7000, material: 'Stone', isOutdoor: false },
    { id: 'WandasWarpHouse', name: "Wanda's Warp House", width: 500, height: 500, material: 'Hardwood', isOutdoor: false },
    { id: 'WandaWestFarmHallway', name: 'Wanda West Farm Hallway', width: 300, height: 20, material: 'Hardwood', isOutdoor: false },
    { id: 'WandaWestBarnWarpHouse', name: 'Wanda West Barn Warp House', width: 400, height: 250, material: 'Hardwood', isOutdoor: false },
    { id: 'WandaEastBrickHallway', name: 'Wanda East Brick Hallway', width: 300, height: 20, material: 'Hardwood', isOutdoor: false },
    { id: 'WandaEastSquareHouse', name: 'Wanda East Square House', width: 800, height: 800, material: 'Hardwood', isOutdoor: false },
    { id: 'PixelGardenGallopDecisionZone', name: 'Pixel Garden Gallop Decision Zone', width: 100, height: 100, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_1', name: 'Pixel Garden Gallop Course 1', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_2', name: 'Pixel Garden Gallop Course 2', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_3', name: 'Pixel Garden Gallop Course 3', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_4', name: 'Pixel Garden Gallop Course 4', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_5', name: 'Pixel Garden Gallop Course 5', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_6', name: 'Pixel Garden Gallop Course 6', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_7', name: 'Pixel Garden Gallop Course 7', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'PixelGardenGallop_Course_8', name: 'Pixel Garden Gallop Course 8', width: 100, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'Adventure_Garden', name: 'Adventure Garden', width: 1000, height: 1000, material: 'Grass', isOutdoor: true },
    { id: 'SelectorHouse', name: 'Selector House', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'Selector_House', name: 'Selector House (Alt)', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'Do_You_Remember_This', name: 'Do You Remember This', width: 15000, height: 400, material: 'Concrete', isOutdoor: true },
    { id: 'AIGeneratedLevel', name: 'AI Generated Level', width: 2000, height: 2000, material: 'Hardwood', isOutdoor: false },
    { id: 'MariasWarpCastle', name: "Maria's Warp Castle", width: 1000, height: 1000, material: 'Stone', isOutdoor: false },
    { id: 'WandaPlatform', name: 'Wanda Platform', width: 100, height: 100, material: 'Stone', isOutdoor: true },
    { id: 'PortalTunnel', name: 'Portal Tunnel', width: 10, height: 200, material: 'Stone', isOutdoor: false },
    { id: 'PoodleRideStoryBookDecisionZone', name: 'Poodle Ride Story Book Decision Zone', width: 50, height: 50, material: 'Hardwood', isOutdoor: false },
    { id: 'PoodleRideStoryBookCourse', name: 'Poodle Ride Story Book Course', width: 400, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Seg1', name: 'Story Book Course 1 Seg 1', width: 500, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Break1', name: 'Story Book Course 1 Break 1', width: 50, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Seg2', name: 'Story Book Course 1 Seg 2', width: 500, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Break2', name: 'Story Book Course 1 Break 2', width: 50, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Seg3', name: 'Story Book Course 1 Seg 3', width: 500, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Break3', name: 'Story Book Course 1 Break 3', width: 50, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookCourse1_Seg4', name: 'Story Book Course 1 Seg 4', width: 1000, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookGoalZone', name: 'Story Book Goal Zone', width: 50, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PoodleRideStoryBookInitialPath', name: 'Story Book Initial Path', width: 400, height: 50, material: 'Hardwood', isOutdoor: true },
    { id: 'PinkHouseFoyer', name: 'Pink House Foyer', width: 500, height: 500, material: 'Hardwood', isOutdoor: false },
    { id: 'PinkHouseTeaRoom', name: 'Pink House Tea Room', width: 400, height: 400, material: 'Hardwood', isOutdoor: false },
    { id: 'PinkHouseDiningRoom', name: 'Pink House Dining Room', width: 400, height: 600, material: 'Hardwood', isOutdoor: false },
    { id: 'PinkHouseKitchen', name: 'Pink House Kitchen', width: 400, height: 200, material: 'Stone', isOutdoor: false },
    { id: 'PrincessTrinikasPathDecisionZone', name: "Princess Trinika's Path Decision Zone", width: 50, height: 50, material: 'Hardwood', isOutdoor: false },
    { id: 'AllisonsDecisionZone', name: "Allison's Decision Zone", width: 100, height: 100, material: 'Hardwood', isOutdoor: false },
    { id: 'PrincessTrinikasRidingPaths', name: "Princess Trinika's Riding Paths", width: 50, height: 26400, material: 'Dirt', isOutdoor: true },
  ],
};
